# Generated by Django 3.1.2 on 2020-10-02 13:42

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(unique=True)),
                ('res_size', models.FloatField()),
                ('res_name', models.CharField(max_length=100)),
                ('res_category', models.CharField(blank=True, max_length=15, null=True)),
                ('res_link', models.CharField(max_length=10000)),
                ('res_thumbnail', models.ImageField(upload_to=myapp.models.Resource.upload_dir)),
            ],
        ),
    ]
