# Generated by Django 3.1.2 on 2020-10-02 13:49

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.Resource.upload_dir),
        ),
    ]
